# Generated by Django 5.2.9 on 2026-01-27 02:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(db_index=True, max_length=50, verbose_name='患者编号')),
                ('sample_code', models.CharField(max_length=50, unique=True, verbose_name='样本条码')),
                ('fastq_r1', models.CharField(max_length=255, verbose_name='R1文件路径')),
                ('fastq_r2', models.CharField(blank=True, max_length=255, null=True, verbose_name='R2文件路径')),
                ('status', models.CharField(choices=[('uploaded', '待分析'), ('running', '分析中'), ('completed', '已完成'), ('failed', '分析失败')], default='uploaded', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交者')),
            ],
            options={
                'verbose_name': '样本管理',
                'verbose_name_plural': '样本管理',
            },
        ),
        migrations.CreateModel(
            name='HRDResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrd_score', models.FloatField(help_text='通常为 LOH+TAI+LST 的总和', verbose_name='HRD总分')),
                ('loh_score', models.IntegerField(verbose_name='LOH评分')),
                ('tai_score', models.IntegerField(verbose_name='TAI评分')),
                ('lst_score', models.IntegerField(verbose_name='LST评分')),
                ('brca_status', models.CharField(choices=[('Positive', '阳性'), ('Negative', '阴性')], max_length=50, verbose_name='BRCA状态')),
                ('variant_data', models.JSONField(blank=True, default=dict, verbose_name='变异详情JSON')),
                ('analysis_date', models.DateTimeField(auto_now_add=True, verbose_name='分析完成时间')),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analysis.sample')),
            ],
            options={
                'verbose_name': '分析结果',
                'verbose_name_plural': '分析结果',
            },
        ),
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Celery任务ID')),
                ('status', models.CharField(choices=[('PENDING', '排队中'), ('STARTED', '计算中'), ('SUCCESS', '成功'), ('FAILURE', '失败'), ('REVOKED', '已取消')], default='PENDING', max_length=20, verbose_name='任务状态')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='参数快照')),
                ('log_output', models.TextField(blank=True, verbose_name='执行日志/错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='任务创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='状态更新时间')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='analysis.sample', verbose_name='关联样本')),
            ],
            options={
                'verbose_name': '分析任务记录',
                'verbose_name_plural': '分析任务记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
