# Generated by Django 5.2.9 on 2026-03-24 16:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_role', models.CharField(choices=[('TUMOR_R1', 'Tumor FASTQ R1'), ('TUMOR_R2', 'Tumor FASTQ R2'), ('NORMAL_R1', 'Normal FASTQ R1'), ('NORMAL_R2', 'Normal FASTQ R2')], db_index=True, max_length=20)),
                ('original_name', models.CharField(max_length=255)),
                ('stored_name', models.CharField(blank=True, default='', max_length=255)),
                ('storage_path', models.CharField(blank=True, default='', max_length=500)),
                ('temp_dir', models.CharField(blank=True, default='', max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('uploaded_size', models.BigIntegerField(default=0)),
                ('chunk_size', models.IntegerField(default=0)),
                ('total_chunks', models.IntegerField(default=0)),
                ('checksum_md5', models.CharField(blank=True, default='', max_length=32)),
                ('upload_status', models.CharField(choices=[('PENDING', '待上传'), ('UPLOADING', '上传中'), ('UPLOADED', '已上传'), ('FAILED', '上传失败'), ('CANCELLED', '已取消')], default='PENDING', max_length=20)),
                ('merge_status', models.CharField(choices=[('PENDING', '待合并'), ('MERGING', '合并中'), ('MERGED', '已合并'), ('FAILED', '合并失败')], default='PENDING', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('upload_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='上传会话ID')),
                ('chunk_size', models.IntegerField(verbose_name='分片大小(Byte)')),
                ('total_size', models.BigIntegerField(verbose_name='文件总大小(Byte)')),
                ('current_offset', models.BigIntegerField(default=0, verbose_name='当前偏移量(Byte)')),
                ('total_chunks', models.IntegerField(default=0, verbose_name='总分片数')),
                ('uploaded_chunks', models.IntegerField(default=0, verbose_name='已上传分片数')),
                ('uploaded_parts', models.JSONField(blank=True, default=list, verbose_name='已上传分片列表')),
                ('status', models.CharField(choices=[('INITIATED', '已初始化'), ('UPLOADING', '上传中'), ('PAUSED', '已暂停'), ('MERGING', '合并中'), ('COMPLETED', '已完成'), ('FAILED', '失败'), ('EXPIRED', '已过期'), ('CANCELLED', '已取消')], db_index=True, default='INITIATED', max_length=20, verbose_name='会话状态')),
                ('client_fingerprint', models.CharField(blank=True, default='', max_length=255, verbose_name='客户端标识')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='最后活跃时间')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '上传会话',
                'verbose_name_plural': '上传会话',
                'db_table': 'analysis_upload_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='analysistask',
            options={'ordering': ['-created_at'], 'verbose_name': '分析任务', 'verbose_name_plural': '分析任务'},
        ),
        migrations.AlterModelOptions(
            name='hrdresult',
            options={'ordering': ['-analysis_date'], 'verbose_name': 'HRD结果', 'verbose_name_plural': 'HRD结果'},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={},
        ),
        migrations.RemoveField(
            model_name='sample',
            name='fastq_r1',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='fastq_r2',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='status',
        ),
        migrations.AddField(
            model_name='analysistask',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='错误信息'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='input_manifest',
            field=models.JSONField(blank=True, default=dict, verbose_name='输入清单'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='result_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='结果路径'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='retry_count',
            field=models.IntegerField(default=0, verbose_name='重试次数'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='task_type',
            field=models.CharField(choices=[('UPLOAD_MERGE', '文件合并'), ('HRD_ANALYSIS', 'HRD分析'), ('REPORT_GENERATE', '报告生成'), ('OTHER', '其他')], db_index=True, default='HRD_ANALYSIS', max_length=30, verbose_name='任务类型'),
        ),
        migrations.AddField(
            model_name='hrdresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hrdresult',
            name='genome_build',
            field=models.CharField(blank=True, default='hg38', max_length=20, verbose_name='参考基因组版本'),
        ),
        migrations.AddField(
            model_name='hrdresult',
            name='input_type',
            field=models.CharField(choices=[('WGS', 'WGS'), ('WES', 'WES'), ('SNP_PANEL', 'SNP Panel')], default='WGS', max_length=20, verbose_name='输入类型'),
        ),
        migrations.AddField(
            model_name='hrdresult',
            name='pipeline_version',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='管道版本'),
        ),
        migrations.AddField(
            model_name='hrdresult',
            name='qc_metrics',
            field=models.JSONField(blank=True, default=dict, verbose_name='质控指标'),
        ),
        migrations.AddField(
            model_name='hrdresult',
            name='report_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='报告路径'),
        ),
        migrations.AddField(
            model_name='hrdresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='sample',
            name='analysis_status',
            field=models.CharField(choices=[('NOT_STARTED', '未开始'), ('QUEUED', '排队中'), ('RUNNING', '分析中'), ('COMPLETED', '已完成'), ('FAILED', '分析失败')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='data_type',
            field=models.CharField(choices=[('WGS', 'WGS'), ('WES', 'WES'), ('SNP_PANEL', 'SNP Panel')], default='WGS', max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sample',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sample',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='sample',
            name='upload_status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('UPLOADING', '上传中'), ('UPLOADED', '已上传'), ('UPLOAD_FAILED', '上传失败')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Celery任务ID'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='log_output',
            field=models.TextField(blank=True, default='', verbose_name='日志输出'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, verbose_name='任务参数'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_tasks', to='analysis.sample', verbose_name='所属样本'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='status',
            field=models.CharField(choices=[('PENDING', '待执行'), ('QUEUED', '排队中'), ('RUNNING', '运行中'), ('SUCCESS', '成功'), ('FAILED', '失败'), ('CANCELLED', '已取消')], db_index=True, default='PENDING', max_length=20, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='hrdresult',
            name='analysis_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='分析时间'),
        ),
        migrations.AlterField(
            model_name='hrdresult',
            name='brca_status',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('VUS', 'VUS')], db_index=True, default='UNKNOWN', max_length=20, verbose_name='BRCA状态'),
        ),
        migrations.AlterField(
            model_name='hrdresult',
            name='hrd_score',
            field=models.FloatField(default=0, verbose_name='HRD总分'),
        ),
        migrations.AlterField(
            model_name='hrdresult',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hrdresult',
            name='loh_score',
            field=models.IntegerField(default=0, verbose_name='LOH分数'),
        ),
        migrations.AlterField(
            model_name='hrdresult',
            name='lst_score',
            field=models.IntegerField(default=0, verbose_name='LST分数'),
        ),
        migrations.AlterField(
            model_name='hrdresult',
            name='sample',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hrd_result', to='analysis.sample', verbose_name='所属样本'),
        ),
        migrations.AlterField(
            model_name='hrdresult',
            name='tai_score',
            field=models.IntegerField(default=0, verbose_name='TAI分数'),
        ),
        migrations.AlterField(
            model_name='hrdresult',
            name='variant_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='变异数据'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sample',
            name='patient_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['sample', 'task_type'], name='analysis_ta_sample__ed00df_idx'),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['sample', 'status'], name='analysis_ta_sample__b329b1_idx'),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['celery_task_id'], name='analysis_ta_celery__90fd6c_idx'),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['created_at'], name='analysis_ta_created_913c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='hrdresult',
            index=models.Index(fields=['brca_status'], name='analysis_hr_brca_st_a2e6b2_idx'),
        ),
        migrations.AddIndex(
            model_name='hrdresult',
            index=models.Index(fields=['analysis_date'], name='analysis_hr_analysi_d2a2a1_idx'),
        ),
        migrations.AlterModelTable(
            name='analysistask',
            table='analysis_task',
        ),
        migrations.AlterModelTable(
            name='hrdresult',
            table='analysis_hrdresult',
        ),
        migrations.AddField(
            model_name='samplefile',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='analysis.sample'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='analysis.samplefile', verbose_name='所属文件'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['upload_id'], name='analysis_up_upload__985eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['file'], name='analysis_up_file_id_333c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['status'], name='analysis_up_status_48869b_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['expires_at'], name='analysis_up_expires_92667a_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['last_activity_at'], name='analysis_up_last_ac_71121d_idx'),
        ),
    ]
