"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!wm7r085jyw0^wp^^=p#ric8*l+f^o5v)8oyxty*#+5$s)plpz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'analysis',
]

REST_FRAMEWORK = {
    # 1. 全局权限配置：默认所有接口都需要身份认证 (IsAuthenticated)
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # 2. 身份认证方式：优先使用 JWT，其次是传统的 Session (方便我们在浏览器后台调试)
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        # 1. 指定使用 MySQL 引擎
        'ENGINE': 'django.db.backends.mysql',
        
        # 2. 数据库名字 (刚才你用 SQL 创建的那个)
        'NAME': 'hrd_db',
        
        # 3. 用户名 (初始化时默认是 root)
        'USER': 'root',
        
        # 4. 密码 (因为用了 --initialize-insecure，所以这里留空)
        'PASSWORD': '',
        
        # 5. 主机地址 (强制使用 TCP 协议)
        'HOST': '127.0.0.1',
        
        # 6. 端口号
        'PORT': '33061',
        
        # 7. 关键选项：指定 Socket 文件路径
        'OPTIONS': {
            'unix_socket': '/data_storage2/shiyi/mysql_data/mysql.sock',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 配置 JWT 参数
from datetime import timedelta

SIMPLE_JWT = {
    # Access Token (访问令牌) 的有效期。为了你开发测试方便，先设为 1 天。
    # 等毕设上线时，可以改成 60 分钟以提高安全性。
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    
    # Refresh Token (刷新令牌) 的有效期。用于当 Access Token 过期时，静默换取新令牌。
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    
    # 令牌前缀，前端发送请求时通常写成 "Bearer xxxx.yyyy.zzzz"
    'AUTH_HEADER_TYPES': ('Bearer',), 
}

# 配置 Celery 
# 消息代理 (Broker) 是本地的 Redis，端口 6379，数据库 0
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
# 结果也存回 Redis (数据库 1)
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/1'
# 接受的内容格式
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
# 时区与 Django 保持一致
CELERY_TIMEZONE = 'Asia/Shanghai'