"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 自动加载仓库根目录 .env（与 .env.example 同级）；已存在于 os.environ 的键不会被覆盖
_REPO_ROOT = BASE_DIR.parent
load_dotenv(_REPO_ROOT / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# 生产环境：必须设置环境变量 DJANGO_SECRET_KEY；勿将真实密钥写入仓库。
# 本地未设置时使用仅用于开发的占位密钥；关闭 DEBUG 时禁止使用占位密钥。
_DEV_PLACEHOLDER_SECRET = "django-insecure-dev-only-not-for-production"
SECRET_KEY = (os.environ.get("DJANGO_SECRET_KEY") or "").strip()
if not SECRET_KEY:
    SECRET_KEY = _DEV_PLACEHOLDER_SECRET

DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() in ("1", "true", "yes")

if not DEBUG and SECRET_KEY == _DEV_PLACEHOLDER_SECRET:
    raise ImproperlyConfigured(
        "生产环境必须设置环境变量 DJANGO_SECRET_KEY，且不能使用开发占位密钥。"
    )

_hosts_raw = (os.environ.get("DJANGO_ALLOWED_HOSTS") or "127.0.0.1,localhost").strip()
ALLOWED_HOSTS = [h.strip() for h in _hosts_raw.split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'analysis',
]

REST_FRAMEWORK = {
    # 1. 全局权限配置：默认所有接口都需要身份认证 (IsAuthenticated)
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # 2. 身份认证方式：优先使用 JWT，其次是传统的 Session (方便我们在浏览器后台调试)
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    'middleware.exception_middleware.GlobalExceptionMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# 凭据通过环境变量提供，参见仓库根目录 .env.example

if "MYSQL_UNIX_SOCKET" in os.environ:
    _mysql_sock = os.environ["MYSQL_UNIX_SOCKET"].strip()
    _db_options = {"unix_socket": _mysql_sock} if _mysql_sock else {}
else:
    _db_options = {"unix_socket": "/data_storage2/shiyi/mysql_data/mysql.sock"}

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("MYSQL_DATABASE", "hrd_db"),
        "USER": os.environ.get("MYSQL_USER", "root"),
        "PASSWORD": os.environ.get("MYSQL_PASSWORD", ""),
        "HOST": os.environ.get("MYSQL_HOST", "127.0.0.1"),
        "PORT": os.environ.get("MYSQL_PORT", "33061"),
        "OPTIONS": _db_options,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 配置 JWT 参数
from datetime import timedelta

SIMPLE_JWT = {
    # Access Token (访问令牌) 的有效期。为了你开发测试方便，先设为 1 天。
    # 等毕设上线时，可以改成 60 分钟以提高安全性。
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    
    # Refresh Token (刷新令牌) 的有效期。用于当 Access Token 过期时，静默换取新令牌。
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    
    # 令牌前缀，前端发送请求时通常写成 "Bearer xxxx.yyyy.zzzz"
    'AUTH_HEADER_TYPES': ('Bearer',), 
}

# 配置 Celery（可用 CELERY_BROKER_URL / CELERY_RESULT_BACKEND 覆盖）
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.environ.get(
    "CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/1"
)
# 接受的内容格式
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
# 时区与 Django 保持一致
CELERY_TIMEZONE = 'Asia/Shanghai'

_hrd_allowed_import_roots = os.environ.get("HRD_ALLOWED_IMPORT_ROOTS", "").strip()
HRD_ALLOWED_IMPORT_ROOTS = [
    root.strip()
    for root in _hrd_allowed_import_roots.split(",")
    if root.strip()
]

# 生信 pipeline（相对仓库根目录，可用环境变量覆盖；_REPO_ROOT 见文件顶部 load_dotenv 处）
HRD_PIPELINE_ROOT = Path(os.environ.get("HRD_PIPELINE_ROOT", _REPO_ROOT / "pipeline"))
HRD_PIPELINE_WORK_ROOT = Path(
    os.environ.get("HRD_PIPELINE_WORK_ROOT", _REPO_ROOT / "pipeline" / "work")
)
# 传给 run_wgs.sh -r；留空则使用脚本内默认参考路径
HRD_WGS_REF_FA = os.environ.get("HRD_WGS_REF_FA", "")
HRD_WGS_THREADS = os.environ.get("HRD_WGS_THREADS", "8")
# 可选：显式指定 Rscript（否则 run_wgs.sh 使用 pipeline/envs/bin/Rscript）
HRD_RSCRIPT = os.environ.get("HRD_RSCRIPT", "")
# WGS 子进程超时（秒）；缺省或 <=0 表示不限制
_hrd_to = os.environ.get("HRD_WGS_SUBPROCESS_TIMEOUT", "").strip()
if _hrd_to:
    _hrd_tov = int(_hrd_to)
    HRD_WGS_SUBPROCESS_TIMEOUT = _hrd_tov if _hrd_tov > 0 else None
else:
    HRD_WGS_SUBPROCESS_TIMEOUT = None

# WES：run_wes.sh 的 -r / -@ / -G；线程与超时未单独配置时与 WGS 共用缺省
HRD_WES_REF_FA = os.environ.get("HRD_WES_REF_FA", HRD_WGS_REF_FA)
HRD_WES_THREADS = os.environ.get("HRD_WES_THREADS", HRD_WGS_THREADS)
HRD_WES_SCAR_REFERENCE = os.environ.get("HRD_WES_SCAR_REFERENCE", "").strip()
_hrd_wes_to = os.environ.get("HRD_WES_SUBPROCESS_TIMEOUT", "").strip()
if _hrd_wes_to:
    _hrd_wes_tov = int(_hrd_wes_to)
    HRD_WES_SUBPROCESS_TIMEOUT = _hrd_wes_tov if _hrd_wes_tov > 0 else None
else:
    HRD_WES_SUBPROCESS_TIMEOUT = HRD_WGS_SUBPROCESS_TIMEOUT

# HRD 阳性判定：总分 >= 该值视为阳性（与前端展示一致；可用环境变量 HRD_POSITIVE_SCORE_MIN 覆盖）
_hrd_pos = os.environ.get("HRD_POSITIVE_SCORE_MIN", "").strip()
if _hrd_pos:
    try:
        _hrd_pos_v = float(_hrd_pos)
        HRD_POSITIVE_SCORE_MIN = _hrd_pos_v if _hrd_pos_v > 0 else 42.0
    except ValueError:
        HRD_POSITIVE_SCORE_MIN = 42.0
else:
    HRD_POSITIVE_SCORE_MIN = 42.0
